# Site settings
title: Workshop Manual HTML/CSS Coding Standards
email: michael.fouquet@me.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _fookay
github_username:  mfouquet

# Build settings
markdown: kramdown
